name: SuperSurvival
version: '${project.version}'
main: me.evasive.supersurvival.SuperSurvival
api-version: 1.17
commands:
  admin:
    description: Admin Skill Commands
    usage: /admin
  skills:
    description: Skill Commands
    usage: /skills
